import React from "react";
import Head from "next/head";

function Header(): JSX.Element {
  return (
    <>
      <Head>
        <title>POS - TIS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Header
    </>
  );
}

export default Header;
