import React from "react";
import Head from "next/head";

function Header(): JSX.Element {
  return (
    <>
      <Head>
        <title>POS - TIS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-orange-500 p-2 h-[6vh]">
        <div className="container mx-auto ">
          <div className="mx-5 flex justify-between">
            <div>
              <span className="text-white font-medium">
                POS - The Islander Shop
              </span>
            </div>
            <div>Report</div>
          </div>
        </div>
      </header>
    </>
  );
}

export default Header;
