import React from "react";
import Head from "next/head";
import Link from "next/link";

function Header(): JSX.Element {
  return (
    <>
      <Head>
        <title>POS - TIS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-orange-500 p-2 h-[6vh]">
        <div className="container mx-auto ">
          <div className="mx-5 flex justify-between">
            <div>
              <span className="text-white font-medium">
                <Link href="/">
                  <a>POS - The Islander Shop</a>
                </Link>
              </span>
            </div>
            <div>
              <ul className="flex flex-row space-x-2">
                <li>Product</li>
                <li>Buyer</li>
                <li>
                  <Link href="/summary">
                    <a>Report Summary</a>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </>
  );
}

export default Header;
